version: "3"

services:
  mongo_db:
    image: mongo:4.0
    restart: always
    volumes:
      - ./db/mongo/data:/data/db
      - ./db/pedidos.json:/json/pedidos.json
      - ./db/producto.json:/json/producto.json
      - ./db/users.json:/json/users.json
    # ports:
    #   - 27018:27017
    # deploy:
    #   placement:
    #     constraints:
    #       - node.hostname == servidorUbuntu
  microuser:
    build: ./microuser
    depends_on:
      - mongo_db
    # ports:
    #   - 3001:3001
